spring.application.name=WEATHERSERVICE
server.port=8124

# ----------------------
# Eureka Client (Service Discovery)
# ----------------------
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
spring.profiles.active=native

###Config server
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.uri=http://localhost:8888/api-gateway/default